[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."scrape-site"]
  timeout = 26

[functions."translate"]
  timeout = 26

[functions."extract-url"]
  timeout = 26

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
